site_name: Scientific Machine Learning (SciML)
site_author: Krishna Kumar
site_description: Course materials for Scientific Machine Learning
site_url: https://github.com/kks32-courses/sciml
repo_url: https://github.com/kks32-courses/sciml
use_directory_urls: false
repo_name: SciML Course Repo

theme:
  name: material
  logo: chishiki.png
  favicon: chishiki.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - announce.dismiss
  
  icon:
    repo: fontawesome/brands/github
  

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_source: true
      ignore_h1_titles: true
      show_input: true
      theme: light
  - git-revision-date-localized:
      type: date
  
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: "🔗"
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  - javascripts/katex.js
  - javascripts/adaptive-width.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Multi-Layer Perceptron: 
    - MLP: 00-mlp/mlp.ipynb
    - Activation Function ReLU: 00-mlp/relu.md
    - UAT: 
      - UAT Proof: 00-mlp/uat-proof.md
      - UAT ReLU demo: 00-mlp/uat.md
    - Regularization: 00-mlp/regularization.md
    - Automatic Differentiation: 00-mlp/ad.md
    - Gradient Descent: 00-mlp/sgd.md
  - Classification:
    - Decision Tree: 00-mlp/00a-classification.ipynb
    - MLP Classification: 00-mlp/00b-mlp-classification.ipynb
    - Binary Cross Entropy: 00-mlp/bce.md
  - PINNs:
    - PINNs oscillator: 01-pinns/pinns.ipynb
    - Soft vs Hard constraint: 01-pinns/poisson.ipynb
    - Adaptive Weights: 01-pinns/adaptive-weights.ipynb
    - Collocation: 01-pinns/collocation.ipynb
    - Inverse analysis: 01-pinns/inverse-heat.ipynb
    - Burgers: 01-pinns/burgers.ipynb
    - Variational formulation: 01-pinns/linear-elastic-fixed.ipynb
  - DeepONet:
    - DeepONet: 02-deeponet/deeponet.ipynb
    - PI-DeepONet: 02-deeponet/pideeponet.ipynb
    - DeepONet Interpretation: 02-deeponet/deeponet-explanation.md
    - DeepONet Batch Einsum: 02-deeponet/einsum.md
  - Function Encoders:
    - Function Encoders: 03-function-encoder/03-function-encoder.ipynb
    - Function Approximation: 03-function-encoder/function_approximation_tutorial.md
    - B2B Operator: 03-function-encoder/03-b2b-operator.ipynb
  - GNS:
    - GNS: 04-gns/gnn.ipynb
  - Fourier Neural Operator:
    - FNO: 05-fno/fno.ipynb
  - Automatic Differentiation:
    - AD: 06-ad/06-ad.ipynb
  - SINDy:
    - SINDy Pendulum: 07-sindy/07b-sindy-pendulum.ipynb
    - SINDy: 07-sindy/07-sindy.ipynb
    - SINDy Experiment: 07-sindy/07a-sindy-experiment.ipynb
    - SINDy Exercise: 07-sindy/07-sindy-exercise.ipynb
  - Neural ODE:
    - Neural ODE: 08-neural-ode/neural-ode.ipynb
    - Adjoint: 08-neural-ode/constrained_optimization_adjoint_methods.md
    - Latent ODE: 08-neural-ode/latent-ode.ipynb
    - Van Der Pol with Function Encoder: 08-neural-ode/vanderpol-function-encoder.ipynb
  - Bayesian SciML:
    - Bayesian Neural Networks: 09-bayes-cnf/09a-bnn.ipynb

copyright: |
  &copy; 2025 <a href="https://github.com/kks32-courses"  target="_blank" rel="noopener">Krishna Kumar</a>
